version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev # Ensure this points to the correct Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start # This requires npm to be installed in the container

  react-test:
    build:
      context: .
      dockerfile: Dockerfile.dev # Use the same Dockerfile as the app service
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test # This runs the tests
